window.STRATEGY_DATA = {
  meta: {
    title: "企业战略体系交互式导图",
    subtitle: "公司战略作业：总体战略、业务单元战略、职能战略",
    description: "本数据用于树状思维导图与关系网络图两种视图的统一渲染。"
  },
  rootId: "enterpriseStrategy",
  nodes: [
    {
      id: "enterpriseStrategy",
      label: "企业战略体系",
      category: "root",
      level: 0,
      parentId: null,
      summary: "企业战略体系由总体战略、业务单元战略和职能战略三部分构成，三者层层衔接、相互支撑。",
      keyPoints: ["决定企业长期发展方向", "统筹不同层级的战略安排", "通过协同实现整体目标"],
      children: ["corporateStrategy", "businessStrategy", "functionalStrategy"],
      position: { x: 520, y: 260 }
    },
    {
      id: "corporateStrategy",
      label: "总体战略",
      category: "strategy",
      level: 1,
      parentId: "enterpriseStrategy",
      summary: "总体战略是企业最高层次的战略，解决企业整体发展方向、业务范围和资源配置问题。",
      keyPoints: ["明确企业做什么业务", "决定企业发展方向和规模", "统筹总体资源配置"],
      children: ["corporateStable", "corporateGrowth", "corporateRetrench"],
      position: { x: 300, y: 120 }
    },
    {
      id: "businessStrategy",
      label: "业务单元战略",
      category: "strategy",
      level: 1,
      parentId: "enterpriseStrategy",
      summary: "业务单元战略针对某一事业部或业务领域制定，重点解决如何在目标市场中获得竞争优势。",
      keyPoints: ["关注市场竞争方式", "强调业务定位和竞争优势", "服务于总体战略目标"],
      children: ["costLeadership", "differentiation", "focusStrategy"],
      position: { x: 300, y: 410 }
    },
    {
      id: "functionalStrategy",
      label: "职能战略",
      category: "strategy",
      level: 1,
      parentId: "enterpriseStrategy",
      summary: "职能战略由市场、生产、人力、财务、研发等部门制定，用于落实总体战略与业务单元战略。",
      keyPoints: ["把战略目标转化为行动方案", "保障资源与执行落地", "通过部门协同提升实施效果"],
      children: [
        "marketingStrategy",
        "operationsStrategy",
        "hrStrategy",
        "financeStrategy",
        "innovationStrategy"
      ],
      position: { x: 760, y: 260 }
    },
    {
      id: "corporateStable",
      label: "稳定战略",
      category: "corporateType",
      level: 2,
      parentId: "corporateStrategy",
      summary: "在原有业务、市场和技术基础上保持现状，适用于外部环境较稳定、企业现有经营较成熟的阶段。",
      keyPoints: ["维持既有经营领域", "风险较低", "强调效率与稳健"],
      children: [],
      position: { x: 120, y: 70 }
    },
    {
      id: "corporateGrowth",
      label: "增长战略",
      category: "corporateType",
      level: 2,
      parentId: "corporateStrategy",
      summary: "通过扩大规模、拓展市场或延伸产业链实现企业成长，是企业追求发展壮大的常见选择。",
      keyPoints: ["追求规模扩张", "可包含一体化与多元化", "需要更强资源投入"],
      children: [],
      position: { x: 120, y: 150 }
    },
    {
      id: "corporateRetrench",
      label: "收缩战略",
      category: "corporateType",
      level: 2,
      parentId: "corporateStrategy",
      summary: "在外部压力或内部经营不佳时，企业通过削减业务、退出市场或压缩规模来降低风险、保存实力。",
      keyPoints: ["减少低效业务", "控制成本与风险", "为后续调整争取空间"],
      children: [],
      position: { x: 120, y: 230 }
    },
    {
      id: "costLeadership",
      label: "成本领先战略",
      category: "businessType",
      level: 2,
      parentId: "businessStrategy",
      summary: "通过降低生产和运营成本，以相对更低的价格参与竞争，从而获取市场份额。",
      keyPoints: ["强调规模经济", "依赖流程效率和成本控制", "适合价格敏感型市场"],
      children: [],
      position: { x: 120, y: 360 }
    },
    {
      id: "differentiation",
      label: "差异化战略",
      category: "businessType",
      level: 2,
      parentId: "businessStrategy",
      summary: "通过产品、服务、品牌或技术的独特性与竞争者形成区隔，从而提升顾客价值与溢价能力。",
      keyPoints: ["强调独特价值", "有利于形成品牌优势", "通常需要营销和研发配合"],
      children: [],
      position: { x: 120, y: 440 }
    },
    {
      id: "focusStrategy",
      label: "集中化战略",
      category: "businessType",
      level: 2,
      parentId: "businessStrategy",
      summary: "聚焦某一细分市场、特定顾客群或局部区域，以更专业的方式形成优势。",
      keyPoints: ["聚焦细分市场", "资源使用更集中", "适合中小企业或专门化经营"],
      children: [],
      position: { x: 120, y: 520 }
    },
    {
      id: "marketingStrategy",
      label: "市场营销战略",
      category: "functionalType",
      level: 2,
      parentId: "functionalStrategy",
      summary: "围绕目标市场、品牌传播和顾客需求满足展开，是形成市场认知和扩大销售的重要保障。",
      keyPoints: ["确定目标市场", "制定品牌和推广策略", "支撑产品价值传递"],
      children: [],
      position: { x: 900, y: 80 }
    },
    {
      id: "operationsStrategy",
      label: "生产运营战略",
      category: "functionalType",
      level: 2,
      parentId: "functionalStrategy",
      summary: "通过流程设计、质量管理和资源利用效率来保障产品供给与成本控制。",
      keyPoints: ["提升生产效率", "优化流程与质量", "支撑成本和交付能力"],
      children: [],
      position: { x: 970, y: 170 }
    },
    {
      id: "hrStrategy",
      label: "人力资源战略",
      category: "functionalType",
      level: 2,
      parentId: "functionalStrategy",
      summary: "围绕人才招聘、培养、激励和组织能力建设展开，是战略落地的人才保障。",
      keyPoints: ["建设关键人才队伍", "优化激励机制", "提升组织执行力"],
      children: [],
      position: { x: 990, y: 270 }
    },
    {
      id: "financeStrategy",
      label: "财务战略",
      category: "functionalType",
      level: 2,
      parentId: "functionalStrategy",
      summary: "通过资金筹措、投资安排和财务风险控制，保障企业资源配置与经营安全。",
      keyPoints: ["进行资金预算与配置", "控制财务风险", "保障战略实施的资源基础"],
      children: [],
      position: { x: 970, y: 370 }
    },
    {
      id: "innovationStrategy",
      label: "研发创新战略",
      category: "functionalType",
      level: 2,
      parentId: "functionalStrategy",
      summary: "通过技术研发、产品迭代和创新机制建设，为企业形成持续竞争优势提供支持。",
      keyPoints: ["推动技术与产品创新", "形成长期竞争优势", "支撑增长与差异化"],
      children: [],
      position: { x: 900, y: 460 }
    }
  ],
  links: [
    { source: "enterpriseStrategy", target: "corporateStrategy", type: "contains", label: "包含" },
    { source: "enterpriseStrategy", target: "businessStrategy", type: "contains", label: "包含" },
    { source: "enterpriseStrategy", target: "functionalStrategy", type: "contains", label: "包含" },
    { source: "corporateStrategy", target: "corporateStable", type: "contains", label: "类型" },
    { source: "corporateStrategy", target: "corporateGrowth", type: "contains", label: "类型" },
    { source: "corporateStrategy", target: "corporateRetrench", type: "contains", label: "类型" },
    { source: "businessStrategy", target: "costLeadership", type: "contains", label: "类型" },
    { source: "businessStrategy", target: "differentiation", type: "contains", label: "类型" },
    { source: "businessStrategy", target: "focusStrategy", type: "contains", label: "类型" },
    { source: "functionalStrategy", target: "marketingStrategy", type: "contains", label: "职能" },
    { source: "functionalStrategy", target: "operationsStrategy", type: "contains", label: "职能" },
    { source: "functionalStrategy", target: "hrStrategy", type: "contains", label: "职能" },
    { source: "functionalStrategy", target: "financeStrategy", type: "contains", label: "职能" },
    { source: "functionalStrategy", target: "innovationStrategy", type: "contains", label: "职能" },
    { source: "corporateStrategy", target: "businessStrategy", type: "guides", label: "指导" },
    { source: "corporateStrategy", target: "functionalStrategy", type: "guides", label: "统领" },
    { source: "businessStrategy", target: "functionalStrategy", type: "requires", label: "依赖" },
    { source: "costLeadership", target: "operationsStrategy", type: "supports", label: "依赖高效率运营" },
    { source: "costLeadership", target: "financeStrategy", type: "supports", label: "依赖成本控制" },
    { source: "costLeadership", target: "hrStrategy", type: "supports", label: "依赖流程执行" },
    { source: "differentiation", target: "marketingStrategy", type: "supports", label: "依赖品牌传播" },
    { source: "differentiation", target: "innovationStrategy", type: "supports", label: "依赖技术创新" },
    { source: "differentiation", target: "hrStrategy", type: "supports", label: "依赖人才支撑" },
    { source: "focusStrategy", target: "marketingStrategy", type: "supports", label: "依赖细分定位" },
    { source: "focusStrategy", target: "financeStrategy", type: "supports", label: "依赖资源聚焦" },
    { source: "corporateGrowth", target: "innovationStrategy", type: "supports", label: "推动创新扩张" },
    { source: "corporateGrowth", target: "marketingStrategy", type: "supports", label: "推动市场拓展" },
    { source: "corporateStable", target: "operationsStrategy", type: "supports", label: "强调稳健运营" },
    { source: "corporateStable", target: "financeStrategy", type: "supports", label: "强调财务稳健" },
    { source: "corporateRetrench", target: "financeStrategy", type: "supports", label: "强调风险控制" },
    { source: "corporateRetrench", target: "hrStrategy", type: "supports", label: "伴随组织调整" }
  ]
};
